@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":PrescriptionListParser" as PrescriptionListParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("delete 1")
activate LogicManager

LogicManager -> PrescriptionListParser : parseCommand("delete 1")
activate PrescriptionListParser

create DeleteCommandParser
PrescriptionListParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> PrescriptionListParser
deactivate DeleteCommandParser

PrescriptionListParser -> DeleteCommandParser : parse("1")
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand
activate DeleteCommand

DeleteCommand --> DeleteCommandParser : d
deactivate DeleteCommand

DeleteCommandParser --> PrescriptionListParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> PrescriptionListParser
destroy DeleteCommandParser

PrescriptionListParser --> LogicManager : d
deactivate PrescriptionListParser

LogicManager -> DeleteCommand : execute(model)
activate DeleteCommand

DeleteCommand -> Model : deletePrescription(1)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand

[<--LogicManager
deactivate LogicManager
@enduml
