@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR
skinparam DefaultFontSize 24

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "PrescriptionList Storage" #F4F6F6{
Class "<<interface>>\nPrescriptionListStorage" as PrescriptionListStorage
Class JsonPrescriptionStorage
Class JsonSerializablePrescriptionList
Class JsonAdaptedPrescription
Class JsonAdaptedDrug
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" PrescriptionListStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> PrescriptionListStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonPrescriptionListStorage .up.|> PrescriptionListStorage
JsonPrescriptionListStorage ..> JsonSerializablePrescriptionList
JsonSerializablePrescriptionList --> "*" JsonAdaptedPrescription
JsonAdaptedPrescription --> "*" JsonAdaptedDrug

@enduml
